### ISSUE TITLE
Le capteur de luminosité mesure la valeur 'inf'

### ISSUE THREAD

**Issue by j-fremont** [j-fremont/weather-station#1]
Cette valeur est transmise par l'ESP sur le topic luminosity, le server reçoit le message mais ne sait pas le traiter et plante.

$ docker logs 13bf5961e6e9

[0] {"sensor":"outside","value":inf}
[0] 
[0] SyntaxError: Unexpected token i in JSON at position 28
[0]     at JSON.parse (<anonymous>)
[0]     at MqttClient.client.on (/usr/src/app/server.js:92:21)
[0]     at MqttClient.emit (events.js:198:13)
[0]     at MqttClient._handlePublish (/usr/src/app/node_modules/mqtt/lib/client.js:1162:12)
[0]     at MqttClient._handlePacket (/usr/src/app/node_modules/mqtt/lib/client.js:351:12)
[0]     at work (/usr/src/app/node_modules/mqtt/lib/client.js:283:12)
[0]     at Writable.writable._write (/usr/src/app/node_modules/mqtt/lib/client.js:294:5)
[0]     at doWrite (/usr/src/app/node_modules/readable-stream/lib/_stream_writable.js:428:64)
[0]     at writeOrBuffer (/usr/src/app/node_modules/readable-stream/lib/_stream_writable.js:417:5)
[0]     at Writable.write (/usr/src/app/node_modules/readable-stream/lib/_stream_writable.js:334:11)
[0] node server.js exited with code 1

**Comment by j-fremont** [comment]
Test des valeurs retournées par les capteurs dans outside.ino, via la fonction isinf().
